package com.yagay.yauto.platform.accessibility

object AccessibilityOperations {
    const val CLICK_TEXT = "accessibility.click_text"
    const val CLICK_TEXT_ADVANCED = "accessibility.click_text_advanced"
    const val CLICK_VIEW_ID = "accessibility.click_view_id"
    const val CLICK_DESCRIPTION = "accessibility.click_description"
    const val LONG_CLICK_TEXT = "accessibility.long_click_text"
    const val INPUT_TEXT = "accessibility.input_text"
    const val INPUT_TEXT_VIEW_ID = "accessibility.input_text_view_id"
    const val GLOBAL_ACTION = "accessibility.global_action"
    const val TAP = "accessibility.gesture.tap"
    const val SWIPE = "accessibility.gesture.swipe"
    const val SCROLL = "accessibility.scroll"
    const val FIND_TEXT = "accessibility.find_text"
    const val FIND_TEXT_ADVANCED = "accessibility.find_text_advanced"
    const val FIND_VIEW_ID = "accessibility.find_view_id"
    const val KEYBOARD_VISIBLE = "accessibility.keyboard_visible"
    const val GET_SCREEN_TEXT = "accessibility.screen_text.get"
    const val GET_VIEW_TEXT = "accessibility.view_text.get"
    const val GET_UI_NODES = "accessibility.ui_nodes.get"
    const val LONG_CLICK_VIEW_ID = "accessibility.long_click_view_id"
    const val FOCUS_VIEW_ID = "accessibility.focus_view_id"
    const val CLEAR_TEXT_VIEW_ID = "accessibility.clear_text_view_id"
    const val SCROLL_VIEW_ID = "accessibility.scroll_view_id"
    const val SELECT_ALL_VIEW_ID = "accessibility.select_all_view_id"
    const val COPY_VIEW_ID = "accessibility.copy_view_id"
    const val CUT_VIEW_ID = "accessibility.cut_view_id"
    const val PASTE_VIEW_ID = "accessibility.paste_view_id"
    const val GET_VIEW_BOUNDS = "accessibility.view_bounds.get"
    const val GESTURE_PATH = "accessibility.gesture.path"
    const val CAPTURE_SCREENSHOT = "accessibility.screenshot.capture"
}
