package com.yagay.yauto.platform.android

import android.content.Context
import com.yagay.yauto.core.registry.FeaturePack

object AndroidFeaturePacks {
    fun all(
        context: Context,
        quickSettingsTiles: QuickSettingsTileController,
        overlaySurfaces: OverlaySurfaceController,
    ): List<FeaturePack> = listOf(
        AndroidFeaturePack(context),
        AndroidCommunicationFeaturePack(context),
        AndroidCommunicationEventFeaturePack(context),
        AndroidControlFeaturePack(context),
        AndroidPackageQueryFeaturePack(context),
        AndroidAppManagementFeaturePack(context),
        AndroidAdvancedSystemFeaturePack(context),
        AndroidSystemConvenienceFeaturePack(context),
        AndroidSystemPowerCoverageFeaturePack(context),
        AndroidInteractionCoverageFeaturePack(context),
        AndroidPrivilegedUtilityFeaturePack(context),
        AndroidPrivilegedStateFeaturePack(),
        AndroidPowerUserFeaturePack(context),
        AndroidNativeEnvironmentFeaturePack(context),
        AndroidReferenceGapFeaturePack(context),
        AndroidReferenceCompletionFeaturePack(context),
        AndroidReferenceCompletionEventFeaturePack(),
        AndroidUsbFeaturePack(context),
        AndroidMediaDeviceFeaturePack(context),
        AndroidAudioFeaturePack(context),
        AndroidMediaTransportFeaturePack(context),
        AndroidSpeechFeaturePack(context),
        AndroidPlaybackFeaturePack(context),
        AndroidOrganizerFeaturePack(context),
        AndroidDeviceDataFeaturePack(context),
        AndroidDeviceUtilityFeaturePack(context),
        AndroidResourceStateFeaturePack(context),
        AndroidConnectivityFeaturePack(context),
        AndroidBluetoothDeviceFeaturePack(context),
        AndroidWifiDetailFeaturePack(context),
        AndroidNetworkUtilityFeaturePack(),
        AndroidNetworkProfileEventFeaturePack(),
        AndroidBluetoothAudioEventFeaturePack(),
        AndroidLocationRadiusFeaturePack(context),
        AndroidLocationEventFeaturePack(),
        AndroidNfcFeaturePack(context),
        AndroidMidiFeaturePack(context),
        AndroidHttpFeaturePack(),
        AndroidFileFeaturePack(),
        AndroidFileEventFeaturePack(),
        AndroidArchiveFeaturePack(),
        AndroidContentUtilityFeaturePack(context),
        AndroidEventFeaturePack(),
        AndroidDerivedEventFeaturePack(),
        AndroidBatteryEventFeaturePack(),
        AndroidIntervalFeaturePack(),
        AndroidStateFeaturePack(context),
        AndroidExtendedStateFeaturePack(context),
        AndroidNotificationControlFeaturePack(),
        AndroidSensorFeaturePack(),
        AndroidShortcutFeaturePack(context),
        AndroidQuickSettingsFeaturePack(quickSettingsTiles),
        AndroidSurfaceFeaturePack(overlaySurfaces),
        AndroidExternalCommandFeaturePack(context),
    )
}
