package com.yagay.yauto.platform.android

import android.content.Context
import com.yagay.yauto.core.registry.FeaturePack

object AndroidFeaturePacks {
    fun all(
        context: Context,
        quickSettingsTiles: QuickSettingsTileController,
        overlaySurfaces: OverlaySurfaceController,
        workspace: com.yagay.yauto.core.storage.WorkspaceRepository,
    ): List<FeaturePack> = listOf(
        AndroidFeaturePack(context),
        AndroidCommunicationFeaturePack(context),
        AndroidCommunicationEventFeaturePack(context),
        AndroidControlFeaturePack(context),
        AndroidPackageQueryFeaturePack(context),
        AndroidAppManagementFeaturePack(context),
        AndroidAdvancedSystemFeaturePack(context),
        AndroidSystemConvenienceFeaturePack(context),
        AndroidSystemPowerCoverageFeaturePack(context),
        AndroidInteractionCoverageFeaturePack(context),
        AndroidPrivilegedUtilityFeaturePack(context),
        AndroidPrivilegedParityFeaturePack(),
        AndroidTetheringFeaturePack(),
        AndroidWifiPrivilegedFeaturePack(),
        AndroidAccountSyncFeaturePack(),
        AndroidDataUsageFeaturePack(context),
        AndroidStopwatchFeaturePack(),
        AndroidMediaStoreEventFeaturePack(),
        AndroidHttpServerFeaturePack(),
        AndroidFoldFeaturePack(),
        AndroidLsposedFeaturePack(),
        AndroidLsposedLifecycleFeaturePack(),
        AndroidPrivilegedStateFeaturePack(),
        AndroidPowerUserFeaturePack(context),
        AndroidNativeEnvironmentFeaturePack(context),
        AndroidReferenceGapFeaturePack(context),
        AndroidReferenceSystemExpansionFeaturePack(context),
        AndroidReferenceUtilityExpansionFeaturePack(context),
        AndroidReferenceControlExpansionFeaturePack(context),
        AndroidReferenceSignalFeaturePack(context),
        AndroidWakeLockFeaturePack(context),
        AndroidTelephonyStateExpansionFeaturePack(context),
        AndroidAccessStateFeaturePack(context),
        AndroidRoleStateFeaturePack(context),
        AndroidWorkProfileFeaturePack(context),
        AndroidRuntimePermissionFeaturePack(context),
        AndroidPersonalDataFeaturePack(context),
        AndroidTelephonyAdvancedFeaturePack(context),
        AndroidCellTowerFeaturePack(context),
        AndroidBiometricFeaturePack(context),
        AndroidReferenceCompletionFeaturePack(context),
        AndroidReferenceCompletionEventFeaturePack(),
        AndroidRemainingParityFeaturePack(context),
        AndroidFinalParityFeaturePack(context),
        AndroidPpnFeaturePack(context),
        AndroidShortXParityFeaturePack(context),
        AndroidShortXStateFeaturePack(),
        AndroidTextProcessingFeaturePack(),
        AndroidRemainingSourceParityFeaturePack(context),
        AndroidShortXRuntimeEventFeaturePack(),
        AndroidShortXTimeFeaturePack(context),
        AndroidInvocationParityFeaturePack(context),
        AndroidLsposedSystemEventFeaturePack(),
        AndroidLegacyParityFeaturePack(context),
        AndroidMacroDroidParityFeaturePack(context),
        AndroidModeFeaturePack(context),
        AndroidMatterFeaturePack(context),
        AndroidWearFeaturePack(context),
        AndroidVendorBridgeFeaturePack(context),
        AndroidStandaloneExportFeaturePack(context, workspace),
        AndroidUsbFeaturePack(context),
        AndroidMediaDeviceFeaturePack(context),
        AndroidAudioFeaturePack(context),
        AndroidMediaTransportFeaturePack(context),
        AndroidMediaSessionEventFeaturePack(),
        AndroidSpeechFeaturePack(context),
        AndroidPlaybackFeaturePack(context),
        AndroidMediaCaptureFeaturePack(context),
        AndroidCameraCaptureFeaturePack(context),
        AndroidVisionFeaturePack(context),
        AndroidOrganizerFeaturePack(context),
        AndroidDeviceDataFeaturePack(context),
        AndroidDeviceUtilityFeaturePack(context),
        AndroidResourceStateFeaturePack(context),
        AndroidConnectivityFeaturePack(context),
        AndroidBluetoothDeviceFeaturePack(context),
        AndroidWifiDetailFeaturePack(context),
        AndroidNetworkUtilityFeaturePack(),
        AndroidNetworkProfileEventFeaturePack(),
        AndroidBluetoothAudioEventFeaturePack(),
        AndroidLocationRadiusFeaturePack(context),
        AndroidSolarFeaturePack(context),
        AndroidLocationEventFeaturePack(),
        AndroidNfcFeaturePack(context),
        AndroidMidiFeaturePack(context),
        AndroidHttpFeaturePack(),
        AndroidWebBridgeFeaturePack(),
        AndroidAiFeaturePack(context),
        AndroidFileFeaturePack(),
        AndroidFileEventFeaturePack(),
        AndroidSystemLogFeaturePack(),
        AndroidArchiveFeaturePack(),
        AndroidContentUtilityFeaturePack(context),
        AndroidShareFeaturePack(),
        AndroidEventFeaturePack(),
        AndroidDerivedEventFeaturePack(),
        AndroidBatteryEventFeaturePack(),
        AndroidIntervalFeaturePack(),
        AndroidStateFeaturePack(context),
        AndroidExtendedStateFeaturePack(context),
        AndroidNotificationControlFeaturePack(),
        AndroidSensorFeaturePack(),
        AndroidShortcutFeaturePack(context),
        AndroidBleFeaturePack(context),
        AndroidScriptFeaturePack(),
        AndroidQuickSettingsFeaturePack(quickSettingsTiles),
        AndroidCustomRecentsFeaturePack(context, overlaySurfaces),
        AndroidTaskerSceneFeaturePack(overlaySurfaces),
        AndroidTaskerAdvancedFeaturePack(context),
        AndroidSurfaceFeaturePack(overlaySurfaces),
        AndroidExternalCommandFeaturePack(context),
    )
}
