package com.yagay.yauto.importer.macrodroid

import com.yagay.yauto.core.importer.SourceFeatureKind
import com.yagay.yauto.core.importer.SourceFeatureMapper

/**
 * Suggested mappings for source features whose payload is not yet decoded losslessly.
 * Import keeps the original compatibility node and only exposes an existing canonical YAuto target
 * as a hint. Source class names below were verified against MacroDroid 5.67.8.
 */
object MacroDroidFeatureSuggestions {
    val mapper = SourceFeatureMapper { sourceType, kind ->
        when (kind) {
            SourceFeatureKind.ACTION -> action(sourceType)
            SourceFeatureKind.EVENT -> event(sourceType)
            SourceFeatureKind.CONDITION -> condition(sourceType)
            SourceFeatureKind.STATE -> null
        } ?: MacroDroidMappings.mapper.targetId(sourceType, kind)
    }

    private fun action(sourceType: String): String? = when (sourceType) {
        "HttpServerResponseAction" -> "android.http_server.respond"
        "SyncAccountAction" -> "android.sync.account.request"
        "GetDataUsedAction" -> "android.data_usage.query"
        "AiLlmQueryAction" -> "ai.llm.query"
        "SummariseTextAction" -> "ai.text.summarize"
        "RewriteTextAction" -> "ai.text.rewrite"
        "ProofreadingAction" -> "ai.text.proofread"
        "TranslateTextAction" -> "ai.text.translate"
        "ImageDescriptionAction" -> "ai.image.describe"
        "GenerateQRCodeAction", "MGenerateQRCodeAction" -> "android.qr.generate"
        "ReadQRCodeAction" -> "android.qr.decode"
        "OCRAction", "ReadScreenshotContentsAction", "CheckTextInScreenshotAction" -> "android.ocr.text"
        "CheckImageOnScreenAction" -> "android.image.match"
        "CheckPixelColorAction" -> "android.image.color.find"
        "GetCalendarEventsAction", "BGetCalendarEventsAction" -> "android.calendar.events.query"
        "GetContactsAction" -> "android.contacts.query"
        "RecordMicrophoneAction", "ORecordMicrophoneAction" -> "android.audio.record.start"
        "TakePictureAction" -> "android.camera.photo.capture"
        "RecordVideoAction" -> "android.camera.video.record"
        "AnswerCallAction" -> "android.phone.answer"
        "RejectCallAction" -> "android.phone.end"
        "MakeCallAction" -> "android.phone.call"
        "JavaScriptAction", "AJavaScriptAction", "SJavaScriptAction" -> "script.javascript.execute"
        "JavaAction" -> "script.beanshell.execute"
        "SetHotspotAction", "USBTetheringAction", "BluetoothTetheringAction" -> "android.network.tether.set"
        "AuthenticateUserAction" -> "android.biometric.authenticate"
        "OverlayDialogAction", "AnimationOverlayAction" -> "surface.overlay.show"
        "BubbleNotificationAction" -> "surface.bubble.show"
        "ConfigureAppNotificationsAction" -> "android.app.notification_settings.open"
        "HeadsUpNotificationsAction" -> "android.notification.heads_up.set"
        "LocalePluginAction" -> "android.plugin.locale.fire"
        "ConfigureWidgetButtonAction" -> "android.widget.configure"
        "RefreshWidgetAction" -> "android.widget.refresh"
        "OptionDialogAction", "SelectionDialogAction" -> "surface.list.show"
        "BlockTouchesAction" -> "surface.touch_blocker.show"
        "EdgeLightingAction" -> "surface.edge_lighting.show"
        "CaptureNextClickXYAction" -> "accessibility.capture_next_click"
        "ReadSoundLevelAction" -> "android.audio.sound_level.measure"
        "RestoreNotificationsAction" -> "android.notification.restore"
        "SetKeyguardAction" -> "android.keyguard.set"
        "SetNFCAction" -> "android.nfc.set"
        "SetLocationModeAction", "SetGPSAction" -> "android.location.enabled.set"
        "SetAutoRotateAction" -> "android.display.auto_rotate.set"
        "SetScreenTimeoutAction" -> "android.display.screen_timeout.set"
        "DarkThemeAction" -> "android.display.dark_mode.set"
        "BatterySaverAction" -> "android.power.battery_saver.set"
        "KeepAwakeAction" -> "android.power.stay_awake.set"
        "SpeakTextAction", "SayTimeAction" -> "android.tts.speak"
        "ScreenOnAction" -> "android.screen.wake"
        "InputKeyEventAction", "PressBackAction" -> "android.input.keyevent"
        "TakeScreenshotAction" -> "android.screen.screenshot"
        "ControlMediaAction" -> "android.media.transport"
        "SetAlarmClockAction" -> "android.alarm.set"
        "AddCalendarEntryAction" -> "android.calendar.event.add"

        "ClearAppDataAction" -> "android.app.data.clear"
        "KillBackgroundAppAction", "CloseApplicationAction" -> "android.app.background.kill"
        "DisableAppAction" -> "android.app.enabled.set"
        "DisplayDensityAction" -> "android.display.density.set"
        "FontScaleAction" -> "android.display.font_scale.set"
        "ForceScreenRotationAction" -> "android.display.rotation.set"
        "RebootAction" -> "android.device.reboot"
        "SecureSettingsAction", "SystemSettingAction" -> "android.settings.value.put"
        "GetInstalledAppsAction" -> "android.app.installed.list"
        "UpdateClipboardAction" -> "android.clipboard.set"
        "JsonParseAction" -> "data.json.parse"
        "JsonOutputAction" -> "data.json.stringify"
        "UDPCommandAction" -> "android.network.udp.send"
        "HttpRequestAction" -> "android.http.request"
        "OpenFileAction" -> "android.file.open"
        "SetWallpaperAction" -> "android.wallpaper.set"
        "ReadFileAction" -> "file.read_text"
        "WriteToFileAction" -> "file.write_text"
        "SetAutoSyncAction" -> "android.sync.master.set"
        "LaunchHomeScreenAction" -> "android.home.launch"
        "CameraFlashLightAction" -> "android.torch.set"
        "SetAirplaneModeAction" -> "android.airplane_mode.set"
        "SetBluetoothAction" -> "android.bluetooth.set"
        "SetDataAction" -> "android.mobile_data.set"
        "SetWifiAction" -> "android.wifi.set"
        "MuteMicrophoneAction" -> "android.audio.microphone_mute.set"
        "SpeakerPhoneAction" -> "android.audio.speakerphone.set"
        "VibrateAction" -> "android.vibrate"
        "SetVolumeAction" -> "android.audio.volume.set"
        "VolumeIncrementDecrementAction" -> "android.audio.volume.adjust"
        "PlaySoundAction" -> "android.audio.play"
        "ShareTextAction" -> "android.share.text"
        "ShellScriptAction" -> "system.shell.execute"
        "ClearNotificationsAction" -> "android.notification.dismiss_all"
        "LaunchActivityAction" -> "android.app.launch"
        "OpenWebPageAction" -> "android.uri.open"
        "AndroidWearAction" -> "android.wear.message.send"
        "WearOsComplicationAction" -> "android.wear.data.put"
        "PebbleAction" -> "android.pebble.notification"
        "SamsungRoutinesAction" -> "android.samsung_routines.control"
        "SetModeAction" -> "android.mode.set"
        "ForceMacroRunAction" -> "core.automation.run"
        "DisableMacroAction", "DeleteMacroAction" -> "core.automation.set_enabled"
        "CancelActiveMacroAction", "TerminateRunningAction", "StopAction" -> "core.automation.cancel"
        "ClearCallLogAction" -> "android.call_log.clear"
        "DeleteSMSAction" -> "android.sms.delete"
        "DisableCameraAction" -> "android.sensor_privacy.camera.set"
        "DemoModeAction" -> "android.systemui.demo"
        "ChangeKeyboardAction" -> "android.ime.set"
        "SetKeyboardAction" -> "android.ime.set"
        "SetLanguageAction" -> "android.app.locale.set"
        "SetDigitalAssistantAction" -> "android.assistant.set"
        "GetLightLevelAction", "SensorReadAction" -> "android.sensor.read"
        "ForceLocationUpdateAction" -> "android.location.current.query"
        "ShareLocationAction" -> "android.share.text"
        "NotificationReplyAction" -> "android.notification.reply"
        "NotificationInteractionAction" -> "android.notification.action"
        "GetTextByViewIdAction", "ReadScreenContentsAction", "CheckTextOnScreenAction" -> "accessibility.ui_nodes.get"
        "AndroidShortcutsAction", "LaunchShortcutAction" -> "android.shortcut.create"
        "SetQuickSettingsStateAction" -> "android.qs_tile.configure"
        "WifiSSIDScanAction" -> "android.wifi.scan.start"
        "ClearDialogAction", "HideSceneAction" -> "surface.overlay.hide"
        "FloatingTextAction" -> "surface.overlay.show"
        "FloatingButtonConfigureAction" -> "surface.buttons.show"
        "MessageDialogAction", "ConfirmNextAction" -> "surface.buttons.show"
        "TextManipulationAction" -> "android.text.process"
        "EncryptDecryptTextAction" -> "data.text.crypto"
        "DeleteVariableAction", "ClearVariablesAction" -> "variable.clear"
        "ClearDictionaryArrayEntryAction" -> "variable.collection.remove"
        "ArrayManipulationAction", "IterateDictionaryAction" -> "variable.collection.remove"
        "ExportMacrosAction" -> "android.workspace.backup.export"
        "ExportLogAction" -> "android.log.export"
        "ClearLogAction" -> "android.logcat.clear"
        "OpenCallLogAction" -> "android.call_log.open"
        "SendSMSAction", "ForwardSMSAction" -> "android.sms.compose"
        "SendEmailAction" -> "android.email.compose"
        "VoiceInputAction" -> "android.voice_input.capture"
        "VoiceSearchAction" -> "android.voice_search.open"
        "SetNotificationBarIconAction" -> "android.notification.ppn.show"
        "SetNotificationSoundAction", "SetRingtoneAction" -> "android.audio.default_sound.set"
        "ShowVolumePopupAction" -> "android.audio.volume_ui.show"
        "CarModeAction" -> "android.car_mode.set"
        "DayDreamAction" -> "android.display.dream.start"
        "InvertColoursAction" -> "android.display.color_inversion.set"
        "ImmersiveModeAction" -> "android.display.immersive.set"
        "ConnectivityCheckAction" -> "android.network.connectivity.check"
        "SetBrightnessAction", "DimScreenAction" -> "android.display.brightness.set"
        "SetVariableAction" -> "variable.set"
        "PauseAction" -> "core.delay"
        "ToastAction" -> "android.toast.show"
        "SendIntentAction" -> "android.intent.send"
        "NotificationAction", "NotifAction" -> "android.notification.show"
        "LaunchAppActivityAction", "LaunchAndPressAction" -> "android.app.launch"
        "FileOperationAction", "FileOperationAllFilesAction", "FileOperationV21Action" -> "file.copy"
        "FileSelectionAction" -> "android.file.open"
        "LogAction" -> "android.log.write"
        "StopWatchAction" -> "android.stopwatch.start"
        else -> null
    }

    private fun event(sourceType: String): String? = when (sourceType) {
        "FingerprintGestureTrigger" -> "android.event.fingerprint_gesture"
        "FoldAngleTrigger", "HingeAngleTrigger" -> "android.event.hinge_angle_changed"
        "NotificationClickTrigger", "NotificationClickedTrigger" -> "android.event.notification_clicked"
        "ScreenTextAppearedTrigger" -> "android.event.screen_text_appeared"
        "HttpServerTrigger" -> "android.event.http_server_request"
        "StopWatchTrigger", "StopwatchTrigger" -> "android.event.stopwatch_reached"
        "DataUsedTrigger" -> "android.event.data_usage_threshold"
        "AppActivityLaunchedTrigger" -> "android.event.activity_lifecycle"
        "BluetoothBeaconTrigger", "JBluetoothBeaconTrigger" -> "android.event.ble_advertisement"
        "LogcatTrigger", "SystemLogTrigger" -> "android.event.system_log_entry"
        "CellTowerTrigger", "FCellTowerTrigger" -> "android.event.cell_tower_changed"
        "HotspotTrigger", "HotSpotTrigger", "USBTetheringTrigger", "UsbTetheringTrigger" -> "android.event.tethering_changed"
        "WorkProfileTrigger" -> "android.event.work_profile_available"
        "BootTrigger", "MacroDroidInitialisedTrigger" -> "android.event.boot"
        "AirplaneModeTrigger" -> "android.event.airplane_mode_changed"
        "AutoRotateChangeTrigger" -> "android.event.auto_rotate_changed"
        "BatterySaverTrigger" -> "android.event.power_save_changed"
        "DarkThemeTrigger" -> "android.event.dark_mode_changed"
        "NFCStateTrigger" -> "android.event.nfc_state_changed"
        "BatteryLevelTrigger", "BatteryTemperatureTrigger" -> "android.event.battery_changed"
        "HeadphonesTrigger" -> "android.event.headset_changed"
        "ClipboardChangeTrigger" -> "android.event.clipboard_changed"
        "DeviceUnlockedTrigger" -> "android.event.user_present"
        "GPSEnabledTrigger" -> "android.event.location_mode_changed"
        "IncomingSMSTrigger" -> "android.event.sms_received"
        "IncomingCallTrigger", "CallActiveTrigger", "CallEndedTrigger", "CallMissedTrigger" -> "android.event.phone_state_changed"
        "IntentReceivedTrigger" -> "android.event.broadcast"
        "NFCTrigger" -> "android.event.nfc_tag"
        "NetworkTransportChangeTrigger", "VpnTrigger", "IpAddressChangeTrigger" -> "android.event.network_changed"
        "NotificationTrigger" -> "android.event.notification_posted"
        "LightSensorTrigger", "ProximityTrigger", "SensorTrigger" -> "android.event.sensor_value"
        "ShakeDeviceTrigger" -> "android.event.shake"
        "WifiConnectionTrigger", "WifiSSIDTrigger" -> "android.event.wifi_changed"
        "SystemTimeTrigger" -> "android.event.time_changed"
        "WeatherTrigger" -> "android.event.weather_changed"
        "SimChangeTrigger" -> "android.event.sim_subscription_changed"
        "WidgetPressedTrigger" -> "android.event.shortcut"
        "ToastTrigger" -> "android.event.toast_shown"
        "OrientationChangeTrigger" -> "android.event.orientation_changed"

        "ApplicationLaunchedTrigger" -> "android.event.app_foreground"
        "AppEnabledTrigger" -> "android.event.package_changed"
        "AutoSyncChangeTrigger" -> "android.event.system_setting_changed"
        "BluetoothTrigger" -> "android.event.bluetooth_state_changed"
        "CameraFlashlightTrigger" -> "android.event.torch_state_changed_filtered"
        "CameraInUseTrigger" -> "android.event.camera_in_use_changed"
        "DataOnOffTrigger" -> "android.event.mobile_data_changed"
        "DayDreamTrigger" -> "android.event.dreaming_started"
        "DockTrigger" -> "android.event.dock_changed"
        "ExternalPowerTrigger" -> "android.event.power_connected"
        "FileChangedTrigger" -> "android.event.file_changed"
        "FlipDeviceTrigger" -> "android.event.sensor_value"
        "FloatingButtonTrigger", "FloatingTextShownHiddenTrigger" -> "android.event.surface_action"
        "GeofenceTrigger" -> "android.event.geofence_transition"
        "InvokedByAnimationOverlayTrigger", "InvokedByDrawerTrigger",
        "InvokedByFloatingTextLongClickTrigger", "InvokedByFloatingTextTrigger",
        "InvokedByOptionDialogTrigger", "InvokedByOverlayBarTrigger",
        "InvokedBySceneTrigger" -> "android.event.surface_action"
        "InvokedByNotificationTrigger", "NotificationButtonTrigger" -> "android.event.ppn_action"
        "InvokedByPowerMenuTrigger" -> "android.event.menu_action"
        "KeyboardOpenCloseTrigger" -> "android.event.window_changed"
        "LocationTrigger" -> "android.event.location_update"
        "MacroFinishedTrigger" -> "core.event.automation_finished"
        "MediaButtonPressedTrigger", "MediaButtonV2Trigger",
        "PowerButtonLongPressTrigger", "PowerButtonToggleTrigger",
        "VolumeButtonTrigger", "VolumeLongPressTrigger" -> "android.event.hardware_key"
        "MediaTrackChangedTrigger", "SpotifyTrigger" -> "android.event.media_track_changed"
        "ModeEnterExitTrigger" -> "android.event.mode_changed"
        "MusicPlayingTrigger" -> "android.event.media_playback_state_changed"
        "NetworkRoamingChangedTrigger" -> "android.event.network_changed"
        "OrientationTrigger" -> "android.event.orientation_changed"
        "OutgoingCallTrigger" -> "android.event.phone_state_changed"
        "PhotoTakenTrigger" -> "android.event.photo_taken"
        "PriorityModeTrigger" -> "android.event.dnd_filter_changed"
        "QuickSettingsTileTrigger" -> "android.event.qs_tile"
        "RegularIntervalTrigger" -> "android.event.interval"
        "ScreenContentTrigger" -> "android.event.screen_content_changed"
        "ScreenshotContentTrigger" -> "android.event.screen_text_appeared"
        "ShareFileTrigger" -> "android.event.share_file_received"
        "ShareTextTrigger" -> "android.event.share_text_received"
        "ShortcutTrigger", "MacroDroidIconLongPressShortcutTrigger" -> "android.event.shortcut"
        "SilentModeTrigger" -> "android.event.ringer_mode_changed"
        "SunriseSunsetTrigger" -> "android.event.sunrise_sunset"
        "SwipeTrigger" -> "android.event.surface_action"
        "SystemSettingTrigger" -> "android.event.system_setting_changed_filtered"
        "TimerTrigger" -> "android.event.stopwatch_reached"
        "UIClickTrigger" -> "android.event.ui_click"
        "UsbDeviceConnectionTrigger" -> "android.event.usb_device_changed"
        "VariableTrigger" -> "core.event.variable_changed"
        "WebHookTrigger", "WebHook2wayTrigger" -> "android.event.http_server_request"
        else -> null
    }

    private fun condition(sourceType: String): String? = when (sourceType) {
        "FoldAngleConstraint", "HingeAngleConstraint" -> "android.condition.hinge_angle"
        "StopWatchConstraint", "StopwatchConstraint" -> "android.condition.stopwatch"
        "DataUsedConstraint" -> "android.condition.data_usage"
        "CellTowerConstraint", "ACellTowerConstraint", "ICellTowerConstraint" -> "android.condition.cell_tower_match"
        "CalendarConstraint" -> "android.condition.calendar_event"
        "MicrophoneRecordingConstraint" -> "android.condition.audio_recording_active"
        "USBTetheringConstraint", "UsbTetheringConstraint", "WiFiHotSpotConstraint", "WiFiHotspotConstraint", "WifiHotSpotConstraint", "WifiHotspotConstraint" -> "android.condition.tethering"
        "WorkProfileConstraint" -> "android.condition.work_profile_available"
        "AutoRotateConstraint" -> "android.condition.auto_rotate"
        "BatterySaverStateConstraint" -> "android.condition.power_save"
        "DarkThemeConstraint" -> "android.condition.dark_mode"
        "LocationModeConstraint", "GPSEnabledConstraint" -> "android.condition.location_enabled"
        "NFCStateConstraint" -> "android.condition.nfc_enabled"
        "BatteryLevelConstraint" -> "android.condition.battery_level"
        "BatteryTemperatureConstraint" -> "android.condition.battery_temperature"
        "HeadphonesConnectionConstraint" -> "android.condition.headset_connected"
        "AppEnabledConstraint" -> "android.condition.app_enabled"
        "ApplicationInstalledConstraint" -> "android.condition.app_installed"
        "TimeSinceBootConstraint" -> "android.condition.uptime_range"
        "TimeOfDayConstraint" -> "time.condition.time_window"
        "DayOfWeekConstraint" -> "time.condition.weekday"
        "SystemSettingConstraint" -> "android.condition.setting_matches"
        "IpAddressConstraint" -> "android.condition.local_address_match"
        "IsRootedConstraint", "ShizukuStateConstraint" -> "android.condition.privileged_backend_available"
        "AutoSyncConstraint" -> "android.condition.master_sync"
        "DeviceLockedConstraint" -> "android.condition.device_locked"
        "MusicActiveConstraint" -> "android.condition.music_active"
        "PriorityModeConstraint" -> "android.condition.dnd_filter"
        "AirplaneModeConstraint" -> "android.condition.airplane_mode"
        "BrightnessConstraint" -> "android.condition.brightness"
        "ExternalPowerConstraint" -> "android.condition.charging_source"
        "InCallConstraint", "PhoneRingingConstraint" -> "android.condition.phone_call_state"
        "NotificationPresentConstraint" -> "android.condition.notification_active"
        "NotificationVolumeConstraint", "VolumeConstraint", "VolumeLevelConstraint" -> "android.condition.audio.stream_volume"
        "ScreenOnOffConstraint" -> "android.condition.screen"
        "SpeakerPhoneConstraint" -> "android.condition.audio.speakerphone"
        "VpnConstraint" -> "android.condition.network_profile"
        "WifiConstraint" -> "android.condition.wifi_network"

        "AccessibilityServiceStateConstraint" -> "android.condition.accessibility_service_access"
        "ActiveApplicationConstraint", "LauncherIsInForegroundConstraint" -> "android.condition.app_foreground"
        "BluetoothConstraint" -> "android.condition.bluetooth_enabled"
        "CameraInUseConstraint" -> "android.condition.reference_signal.camera_in_use"
        "ClipboardConstraint" -> "android.condition.clipboard_content"
        "CompareValueConstraint" -> "variable.equals"
        "DataOnOffConstraint" -> "android.condition.mobile_data_enabled"
        "DayOfMonthConstraint" -> "time.condition.day_of_month"
        "DeviceOrientationConstraint" -> "android.condition.reference.display_rotation"
        "DrawerStateConstraint", "FloatingButtonConstraint", "FloatingTextConstraint",
        "CustomSceneConstraint", "EdgeLightShowingConstraint" -> "surface.condition.shown"
        "GeofenceConstraint" -> "android.condition.location_radius"
        "IsRoamingConstraint" -> "android.condition.network_roaming"
        "KeyboardShowingConstraint" -> "android.condition.keyboard_visible"
        "LightLevelConstraint", "ProximitySensorConstraint", "SensorValueConstraint",
        "FaceUpDownConstraint" -> "android.condition.sensor_value"
        "MacroDroidVariableConstraint" -> "variable.equals"
        "MacroEnabledConstraint" -> "core.automation.enabled"
        "MacroRunningConstraint" -> "core.automation.running"
        "ModeConstraint" -> "android.condition.mode"
        "MonthOfYearConstraint" -> "time.condition.month_of_year"
        "QuickTileStateConstraint" -> "android.condition.qs_tile_state"
        "SpeakingTextConstraint" -> "android.condition.tts_speaking"
        "SunsetSunriseConstraint" -> "android.condition.daylight"
        "TorchConstraint" -> "android.condition.torch_on"
        "TriggerThatInvokedConstraint", "InvocationMethodConstraint" -> "core.condition.event_tag"
        "UsbDeviceConnectedConstraint" -> "android.condition.usb_device_connected"
        else -> null
    }
}
