package com.yagay.yauto.importer.shortx

import com.yagay.yauto.core.importer.AutomationImporter
import com.yagay.yauto.core.importer.ImportInput
import com.yagay.yauto.core.importer.ImportResult

/**
 * Adds safe native-target hints without changing ShortX decoding semantics.
 * The original compatibility payload remains intact whenever a source message is not decoded.
 */
class EnhancedShortXImporter(
    private val delegate: ShortXImporter = ShortXImporter(),
) : AutomationImporter {
    override val id: String get() = delegate.id
    override val displayName: String get() = delegate.displayName

    override fun confidence(input: ImportInput): Int = delegate.confidence(input)

    override fun import(input: ImportInput): ImportResult {
        val result = delegate.import(input)
        if (result.issues.isEmpty()) return result
        return result.copy(
            issues = result.issues.map { issue ->
                if (issue.suggestedFeatureId != null) issue
                else issue.copy(
                    suggestedFeatureId = ShortXFeatureSuggestions.target(
                        sourceType = issue.sourceType,
                        sourcePath = issue.sourcePath,
                    )
                )
            }
        )
    }
}

/**
 * APK-verified ShortX 1.11 source-type catalogue mapped onto existing canonical YAuto features.
 * These are hints only: a compatibility node keeps the complete source payload until a field-level
 * decoder proves that the conversion is lossless.
 */
internal object ShortXFeatureSuggestions {
    fun target(sourceType: String?, sourcePath: String): String? {
        val name = sourceType?.substringAfterLast('/')?.substringAfterLast('.')?.substringAfterLast('$').orEmpty()
        return when {
            ".action[" in sourcePath -> action(name)
            ".fact[" in sourcePath -> fact(name)
            ".condition[" in sourcePath -> condition(name)
            else -> null
        }
    }

    private fun action(name: String): String? = when (name) {
        "SetNFCEnabled", "ToggleNFC", "EnableNFC", "DisableNFC" -> "android.nfc.set"
        "SetLocationEnabled", "ToggleLocation", "EnableLocation", "DisableLocation" -> "android.location.enabled.set"
        "SetScreenRotate" -> "android.display.rotation.set"
        "SetScreenTimeout" -> "android.display.screen_timeout.set"
        "SetDarkModeEnabled", "ToggleDarkMode", "EnableDarkMode", "DisableDarkMode" -> "android.display.dark_mode.set"
        "StayAwake", "ScreenStayAwake" -> "android.power.stay_awake.set"
        "SetMasterSync" -> "android.sync.master.set"
        "TTS" -> "android.tts.speak"
        "WakeupScreen", "ScreenOn" -> "android.screen.wake"
        "SleepScreen", "LockDeviceNow" -> "system.screen.sleep"
        "InjectKeyCode", "InjectCombineKeyCode" -> "android.input.keyevent"
        "TakeScreenshot", "Screenshot" -> "android.screenshot.capture"
        "MediaPlaybackAction", "MediaPlayback" -> "android.media.transport"
        "SetAppEnabled", "SetAppEnabledByPkg", "DisableApp", "DisableAppByPkg", "EnableApp", "EnableAppByPkg" -> "android.app.enabled.set"
        "SetAppInactive", "SetAppInactiveByPkg" -> "android.app.inactive.set"
        "SetAppSuspend", "SetAppSuspendByPkg", "SuspendApp", "SuspendAppByPkg", "UnSuspendApp", "UnSuspendAppByPkg" -> "android.app.suspended.set"
        "GetAppInfo" -> "android.app.package_info"
        "ScreenBrightness", "SetBrightness", "SetAutoBrightness", "ToggleAutoBrightness", "EnableAutoBrightness", "DisableAutoBrightness", "ContinuousAdjustBrightness" -> "android.display.brightness.set"
        "SetWallpaper" -> "android.wallpaper.set"
        "ReadClipboard" -> "android.clipboard.get"
        "WriteClipboard" -> "android.clipboard.set"
        "CreatePkgSet" -> "android.package_set.create"
        "AddAppsToPkgSetByPkg" -> "android.package_set.add"
        "RemoveAppsFromPkgSetByPkg" -> "android.package_set.remove"
        "CreateGV", "WriteGV" -> "variable.global.set"
        "DeleteGV" -> "variable.global.clear"
        "CreateLocalVar", "WriteLocalVar" -> "variable.set"
        "HttpRequest" -> "android.http.request"
        "LaunchApp", "LaunchAppByPkg" -> "android.app.launch"
        "StopApp", "StopAppByPkg", "StopCurrentApp" -> "android.app.force_stop"
        "ShellCommand" -> "system.shell.execute"
        "InputTap" -> "accessibility.gesture.tap"
        "InputSwipe" -> "accessibility.gesture.swipe"
        "InputText" -> "accessibility.input_text"
        "FindAndClickViewByText", "FindAndClickMatchedView" -> "accessibility.click_text"
        "FindAndClickViewById" -> "accessibility.click_view_id"
        "ShowToast" -> "android.toast.show"
        "OpenUrl" -> "android.uri.open"
        "SetFlashLightEnabled", "ToggleFlashLight", "EnableFlashLight", "DisableFlashLight" -> "android.torch.set"
        "SetDNDEnabled", "ToggleDND", "EnableDND", "DisableDND" -> "android.dnd.set"
        "SetBTEnabled", "ToggleBT", "EnableBT", "DisableBT" -> "android.bluetooth.set"
        "SetWifiEnabled", "ToggleWifi", "EnableWifi", "DisableWifi" -> "android.wifi.set"
        "SetAPMModeEnabled" -> "android.airplane_mode.set"
        "SetDataEnabled", "ToggleData", "EnableData", "DisableData" -> "android.mobile_data.set"
        "PostNotification" -> "android.notification.show"
        "ShowPPN" -> "android.notification.ppn.show"
        "RemovePPN" -> "android.notification.ppn.remove"
        "RemoveNotification", "RemoveNotificationForPackage", "RemoveNotificationForPackageByPkg" -> "android.notification.dismiss"
        "ClickNotification" -> "android.notification.open"
        "ClickNotificationActionButton" -> "android.notification.action"
        "Vibrate" -> "android.vibrate"
        "SetRingerMode" -> "android.audio.ringer_mode.set"
        "SetVolume" -> "android.audio.volume.set"
        "AdjustVolume", "ContinuousAdjustVolume" -> "android.audio.volume.adjust"
        "PlayRingtone" -> "android.audio.play"
        "ExpandNotification" -> "system.notifications.expand"
        "SendSMS" -> "android.sms.compose"
        "ShareContent" -> "android.share.text"
        "Delay" -> "core.delay"
        "KillProcessByName" -> "android.process.kill_by_name"
        "StartAppProcess", "StartAppProcessByPkg" -> "android.app.launch"
        "SetSensorsOffEnabled", "ToggleSensorsOff", "EnableSensorsOff", "DisableSensorsOff" -> "android.sensors_off.set"
        "ShowOverlayButton", "ShowOverlay" -> "surface.overlay.show"
        "HideOverlayButton", "HideOverlay" -> "surface.overlay.hide"
        "HideAllOverlay" -> "surface.overlay.hide_all"
        "SelectScreenArea" -> "surface.region_selector.show"
        "InjectGestureRecording" -> "accessibility.gesture.path"
        "StartGestureRecording", "ToggleGestureRecording" -> "surface.gesture_recorder.show"
        "StopGestureRecording" -> "surface.overlay.hide"
        "GetTextFromScreenNode" -> "accessibility.ui_nodes.get"
        "EnableViewIdViewer" -> "accessibility.view_id_viewer.show"
        "EnableUniversalCopy" -> "accessibility.universal_copy.show"
        "GetCurrentLocationInfo" -> "android.location.current.query"
        "GetCurrentLocationAddress" -> "android.location.reverse_geocode"
        "SetHotSpotEnabled", "ToggleHotSpot", "EnableHotSpot", "DisableHotSpot" -> "android.network.tether.set"
        "Toggle5G" -> "android.telephony.network_mode.set"
        "SwitchMobileDataSlot" -> "android.sim.default_data.set"
        "TakePhoto" -> "android.camera.photo.capture"
        "ScreenFlash" -> "surface.screen_flash.show"
        "ShowDanmu" -> "surface.danmu.show"
        "ShowRecentApps" -> "accessibility.recents.show"
        "ShowCustomRecents" -> "surface.custom_recents.show"
        "AudioRecording" -> "android.audio.record.start"
        "StopAudioRecording" -> "android.audio.record.stop"
        "BiometricVerify" -> "android.biometric.authenticate"
        "ConnectWifi" -> "android.wifi.network.connect"
        "DisconnectCurrentWifi" -> "android.wifi.network.disconnect"
        "DisplayImage" -> "surface.image.show"
        "DownloadFile" -> "android.http.download"
        "GenerateQRCode" -> "android.qr.generate"
        "ParseQRCode" -> "android.qr.decode"
        "OcrDetect" -> "android.ocr.text"
        "FindImagePosition" -> "android.image.match"
        "FindPointsByColor" -> "android.image.color.find"
        "FindPointsByColorAndClick" -> "accessibility.screen_color.find_and_click"
        "PanoramicLightEffect" -> "surface.edge_lighting.show"
        "ShowAlertDialog" -> "surface.buttons.show"
        "ShowChoiceDialog", "ShowListDialog", "ShowMenuDialog" -> "surface.list.show"
        "ShowTextFieldDialog" -> "surface.input.show"
        "ShowClipboardView" -> "accessibility.universal_copy.show"
        "ShowStatusBarChip" -> "surface.chip.show"
        "HideStatusBarClip" -> "surface.overlay.hide"
        "WebDavGet", "WebDavList", "WebDavPut" -> "android.webdav.request"
        "WebSocketConnect" -> "android.websocket.connect"
        "WebSocketSend" -> "android.websocket.send"
        "PluginAction" -> "android.plugin.locale.fire"
        "PerformContextMenuAction" -> "accessibility.context_menu.perform"
        "ClickTile" -> "android.qs_tile.click"
        "ShowGlobalActionsMenu" -> "android.global_actions.show"
        "ShowHideInsets" -> "android.insets.immersive.set"
        "StopService" -> "android.service.stop"
        "CloseActivity" -> "android.activity.close"
        "RemoveTasks", "RemoveTasksByPkg" -> "android.tasks.remove"
        "WaitForIdle" -> "android.ui.wait_for_idle"
        "ScrollViewTo" -> "accessibility.scroll_to"
        "ContinuousGesturePointer" -> "accessibility.pointer.show"
        "StartLastApp" -> "android.app.last_used.launch"
        "LaunchPinedItem", "AppShortcut" -> "android.intent_uri.launch"
        "StartActivity", "StartActivityIntent", "StartActivityIntentUri", "StartActivityUrlSchema" -> "android.external.intent.invoke"
        "StartService" -> "android.external.intent.invoke"
        "MapNav", "MapApp" -> "android.maps.open"
        "SetStatusBarIcon" -> "android.notification.ppn.show"
        "RemoveStatusBarIcon" -> "android.notification.ppn.remove"
        "SetRuleEnabled" -> "core.automation.set_enabled"
        "GetScreenOnTime" -> "android.screen_on_time.get"
        "MatchRegex" -> "data.regex.matches"
        "ReplaceRegex" -> "data.regex.replace"
        "TextProcessing" -> "android.text.process"
        "ExportBackup" -> "android.workspace.backup.export"
        "MapQueryBus" -> "android.maps.bus_query"
        "ToggleSlot" -> "android.telephony.slot.set"
        "RequestAudioFocus" -> "android.audio.focus.request"
        "ExecuteMVEL", "RemoteExecuteMVEL", "MVEL", "RemoteMVEL" -> "script.mvel.execute"
        "ExecuteJS" -> "script.javascript.execute"
        "AreaScreenshot" -> "accessibility.screenshot.capture"
        "DrawBoard", "ShowDrawBoard" -> "surface.draw_board.show"
        "ShowPieMenu", "PieMenu" -> "surface.pie.show"
        "ShowSidebar", "Sidebar" -> "surface.sidebar.show"
        "ShowFloatButton", "FloatingButton" -> "surface.bubble.show"
        "ShowFloatWindow" -> "surface.overlay.show"
        "HideFloatWindow" -> "surface.overlay.hide"
        "ShowActionSidebar", "ShowSideBar" -> "surface.sidebar.show"
        "HideSideBar" -> "surface.overlay.hide"
        "ShowStatusBarChip" -> "surface.chip.show"
        "ShowDrawBoard" -> "surface.draw_board.show"
        else -> ShortXMappings.suggestedActionFeature(name)
    }

    private fun fact(name: String): String? = when (name) {
        "TaskRemoved", "TaskRemovedAny" -> "android.event.task_removed"
        "BackNavStart" -> "android.event.back_navigation_started"
        "BackNavDone" -> "android.event.back_navigation_finished"
        "DeepLinkCall" -> "android.event.deep_link"
        "BrowserIntercept" -> "android.event.browser_intercept"
        "OnMenuActionTrigger" -> "android.event.menu_action"
        "OnStartOp" -> "core.event.automation_started"
        "OnFinishOp" -> "core.event.automation_finished"
        "APMStatusChanged" -> "android.event.airplane_mode_changed"
        "BTStatusChanged" -> "android.event.bluetooth_state"
        "BTConnectedTo", "BTDisconnectedFrom" -> "android.event.bluetooth_device_connection"
        "BatteryLevelChanged", "BatteryTemperatureChanged" -> "android.event.battery_changed"
        "ChargerPlug" -> "android.event.power_connected"
        "ChargerUnplug" -> "android.event.power_disconnected"
        "ClipboardContentChanged" -> "android.event.clipboard_changed"
        "GlobalVarChanged" -> "core.event.variable_changed"
        "DarkModeStatusChanged" -> "android.event.dark_mode_changed"
        "LocationStatusChanged" -> "android.event.location_mode_changed"
        "NFCStatusChanged" -> "android.event.nfc_state_changed"
        "NFCTagDiscover" -> "android.event.nfc_tag"
        "ScreenRotate", "ScreenRotateTrigger" -> "android.event.orientation_changed"
        "ScreenOn" -> "android.event.screen_on"
        "ScreenOff" -> "android.event.screen_off"
        "UserPresent" -> "android.event.user_present"
        "HeadsetPlug" -> "android.event.headset_changed"
        "AppAdded" -> "android.event.package_added"
        "AppRemoved" -> "android.event.package_removed"
        "AppUpdated" -> "android.event.package_replaced"
        "NotificationPosted" -> "android.event.notification_posted"
        "NotificationRemoved" -> "android.event.notification_removed"
        "NotificationUpdated" -> "android.event.notification_updated"
        "Broadcast" -> "android.event.broadcast"
        "CallStateChanged" -> "android.event.phone_state_changed"
        "ShakeDevice" -> "android.event.shake"
        "AccelerometerSensor", "LightSensor", "ProximitySensor", "SensorValueTrend" -> "android.event.sensor_value"
        "WifiConnectedTo", "WifiDisconnectedFrom", "WifiStatusChanged", "ConnectedWifiSignalLevelChanged" -> "android.event.wifi_changed"
        "VPNConnected", "VPNDisconnected" -> "android.event.network_changed"
        "MobileDataStatusChanged" -> "android.event.mobile_data_changed"
        "AudioFocusChanged", "AudioFocusGain", "AudioFocusLost" -> "android.event.audio_focus_changed"
        "MethodHook" -> "android.event.lsposed_method_called"
        "FingerprintGesture", "FingerprintGestureTrigger" -> "android.event.fingerprint_gesture"
        "AdvancedKeyEvent", "CombineKeyEvent", "KeyEvent" -> "android.event.hardware_key"
        "CornerSwipeToCenter", "EdgeGesture", "ScreenGesture" -> "android.event.surface_action"
        "ScreenTextAppeared", "ScreenContentTrigger" -> "android.event.screen_text_appeared"
        "ActivityStarted", "ActivityStopped", "ActivityDestroyed", "AnyActivityStarted", "AnyActivityStopped", "AnyActivityDestroyed" -> "android.event.activity_lifecycle"
        "AppBecomeForeground" -> "android.event.app_foreground"
        "AppBecomeBackground" -> "android.event.app_background"
        "AppGainWindowFocus", "AppLostWindowFocus" -> "android.event.window_changed"
        "OnQSTileClick" -> "android.event.qs_tile"
        "OnStartDynamicShortcut" -> "android.event.shortcut"
        "IMEVisibilityChange" -> "android.event.window_changed"
        "WindowRotationChange" -> "android.event.orientation_changed"
        "AppProcessStarted", "PkgStartRunning", "PkgStartRunningAny" -> "android.event.app_process_started"
        "AppProcessRemoved", "PkgStopRunning", "PkgStopRunningAny" -> "android.event.app_process_stopped"
        "MediaStoreInsert" -> "android.event.media_store_inserted"
        "MediaStoreDelete" -> "android.event.media_store_deleted"
        "HotSpotStatusChanged" -> "android.event.tethering_changed"
        "FlashLightStatusChanged" -> "android.event.torch_state_changed"
        "DNDStatusChanged" -> "android.event.dnd_filter_changed"
        "Logcat" -> "android.event.system_log_entry"
        "SystemSettingsChanged" -> "android.event.system_setting_changed"
        "SunRiseSet" -> "android.event.sunrise_sunset"
        "SystemReady" -> "android.event.boot"
        "Alarm" -> "android.event.alarm_time"
        "FixedInPeriod" -> "android.event.fixed_in_period"
        "RandomInPeriod" -> "android.event.random_in_period"
        "ScreenOnTime" -> "android.event.screen_on_duration"
        "CpuAvgAvailability" -> "android.event.cpu_availability"
        "Sound" -> "android.event.sound_level"
        "UserPresentAtTheFirstTime" -> "android.event.user_present_first_after_boot"
        "AnyFact" -> "core.event.any"
        "Notification" -> "android.event.notification_posted"
        "HasFoundNodeOnScreen" -> "android.event.screen_text_appeared"
        "ProximitySensorStateChanged" -> "android.event.sensor_value"
        "UsbDeviceAttached", "UsbDeviceDetached" -> "android.event.usb_device_changed"
        "IncomingShare" -> "android.event.share_text_received"
        else -> null
    }

    private fun condition(name: String): String? = when (name) {
        "BatteryPercent", "BatteryLevel" -> "android.condition.battery_level"
        "BatteryTemperature" -> "android.condition.battery_temperature"
        "IsHeadsetPlug" -> "android.condition.headset_connected"
        "AppIsRunning", "AppIsNotRunning", "ProcessIsRunning" -> "android.condition.app_process_running"
        "ServiceIsRunning" -> "android.condition.service_running"
        "AppHasTask", "AppHasTaskByPkg" -> "android.condition.task_present"
        "AppHasWindowFocus", "CurrentForegroundApp", "CurrentForegroundAppByPkg" -> "android.condition.app_foreground"
        "EvaluateContextVar", "EvaluateGlobalVar", "EvaluateLocalVar" -> "variable.equals"
        "JS" -> "script.javascript.condition"
        "MVEL" -> "script.mvel.condition"
        "RequireBTConnected", "RequireBTDisconnected", "RequireBTDeviceFound" -> "android.condition.bluetooth_device_connected"
        "RequireNotificationPanelExpanded" -> "android.condition.notification_panel_expanded"
        "TRUE" -> "core.boolean"
        "RequireMobileDataEnabled" -> "android.condition.mobile_data_enabled"
        "AppHasAudioFocus" -> "android.condition.reference.audio_focus_held"
        "ScreenIsOn" -> "android.condition.screen"
        "AvailableMemory" -> "android.condition.memory_available"
        "ChargeState", "PlugState", "PlugType" -> "android.condition.charging_source"
        "AppHasNotification" -> "android.condition.notification_active"
        "TimeInRange", "TheXXTimeToday", "TheXXTimeTodayScope" -> "time.condition.time_window"
        "KeyguardIsLocked" -> "android.condition.device_locked"
        "RequireIMEVisibility" -> "android.condition.keyboard_visible"
        "CurrentActivity" -> "android.condition.app_foreground"
        "RequireTileState" -> "android.condition.qs_tile_state"
        "RequireWindowRotation" -> "android.condition.reference.display_rotation"
        "RequireAPMMode" -> "android.condition.airplane_mode"
        "RequireWifiConnected", "RequireWifiDisconnected", "ConnectedWifiSignal" -> "android.condition.wifi_network"
        "RequireRingerMode" -> "android.condition.audio.ringer_mode"
        "ScreenStayAwake" -> "android.condition.stay_awake_while_charging"
        "FlashlightIsOn" -> "android.condition.torch_on"
        "TextFromScreenNodeMatches", "HasNodeOnScreen" -> "accessibility.condition.text_matches"
        "HasFoundPointsByColor" -> "accessibility.condition.screen_color_found"
        "MatchMVEL" -> "script.mvel.condition"
        "MatchJS" -> "script.javascript.condition"
        "VPNIsConnected" -> "android.condition.network_profile"
        "IsRuleEnabled" -> "core.automation.enabled"
        "IsInCall", "IsRinging" -> "android.condition.phone_call_state"
        "FoldAngle", "FoldAngleCondition", "HingeAngle" -> "android.condition.hinge_angle"
        "RequireScreenRotate" -> "android.condition.reference.display_rotation"
        "RequireSensorOff" -> "android.condition.sensors_off"
        "CalendarDayMatch" -> "android.condition.calendar_day_type"
        "RequireDelay" -> "core.condition.delay"
        "RequireFactTag" -> "core.condition.event_tag"
        "ScreenOrientationIsPort" -> "android.condition.reference.orientation"
        "EvaluateScreenOnTime" -> "android.condition.screen_on_time"
        "True" -> "core.boolean"
        "False" -> "core.boolean"
        else -> null
    }
}
