package com.yagay.yauto.importer.shortx

/** Central source-name hints. Hints are not native import support. */
internal object ShortXNativeSuggestionCatalog {
    fun suggestedConditionFeature(typeUrl: String): String? = when (ShortXMappings.shortName(typeUrl)) {
        "CurrentPkgList", "CurrentPkgListByPkg", "CurrentActivity" -> "android.condition.app_foreground"
        "BatteryPercent" -> "android.condition.battery_level"
        "AvailableMemory" -> "android.condition.memory_available"
        "ConnectedWifiSignal", "RequireWifiConnected", "RequireWifiDisconnected" -> "android.condition.wifi_network"
        "AppIsRunning", "AppIsNotRunning", "ProcessIsRunning" -> "android.condition.app_process_running"
        "EvaluateScreenOnTime" -> "android.condition.screen_on_time"
        "ScreenIsOn" -> "android.condition.screen"
        "VPNIsConnected" -> "android.condition.network_profile"
        "ChargeState" -> "android.condition.charging"
        "PlugState" -> "android.condition.charging_source"
        "RequireMobileDataEnabled" -> "android.condition.mobile_data_enabled"
        "AppHasNotification" -> "android.condition.notification_active"
        "KeyguardIsLocked" -> "android.condition.keyguard_locked"
        "ScreenOrientationIsPort", "RequireScreenRotate", "RequireWindowRotation" -> "android.condition.orientation"
        "IsInCall", "IsRinging" -> "android.condition.phone_call_state"
        "IsHeadsetPlug" -> "android.condition.headset_connected"
        "RequireAPMMode" -> "android.condition.airplane_mode"
        "RequireRingerMode" -> "android.condition.ringer_mode"
        "RequireIMEVisibility" -> "android.condition.ime_visible"
        "RequireNotificationPanelExpanded" -> "android.condition.notification_panel_expanded"
        else -> null
    }

    fun suggestedEventFeature(typeUrl: String): String? = when (ShortXMappings.shortName(typeUrl)) {
        "ScreenOn" -> "android.event.screen_on"
        "ScreenOff" -> "android.event.screen_off"
        "UserPresent", "UserPresentAtTheFirstTime" -> "android.event.user_present"
        "BatteryLevelChanged", "BatteryTemperatureChanged" -> "android.event.battery_changed"
        "ChargerPlug" -> "android.event.power_connected"
        "ChargerUnplug" -> "android.event.power_disconnected"
        "AppBecomeFg" -> "android.event.app_foreground"
        "AppBecomeBg" -> "android.event.app_background"
        "BTStatusChanged" -> "android.event.bluetooth_state"
        "WifiStatusChanged" -> "android.event.wifi_adapter_state_filtered"
        "WifiConnectedTo", "WifiDisconnectedFrom", "ConnectedWifiSignalLevelChanged" -> "android.event.wifi_changed"
        "NFCStatusChanged" -> "android.event.nfc_state_changed"
        "LocationStatusChanged" -> "android.event.location_mode_changed"
        "DarkModeStatusChanged" -> "android.event.dark_mode_changed"
        "APMStatusChanged" -> "android.event.airplane_mode_changed"
        "NotificationPosted" -> "android.event.notification_posted"
        "NotificationRemoved" -> "android.event.notification_removed"
        "AppAdded" -> "android.event.package_added"
        "AppRemoved" -> "android.event.package_removed"
        "AppUpdated" -> "android.event.package_replaced"
        "Broadcast" -> "android.event.broadcast"
        "VPNConnected", "VPNDisconnected" -> "android.event.network_profile_changed"
        "CallStateChanged" -> "android.event.phone_state_changed"
        "ClipboardContentChanged" -> "android.event.clipboard_changed"
        "HeadsetPlug" -> "android.event.headset_changed"
        "NFCTagDiscover" -> "android.event.nfc_tag"
        "KeyEvent" -> "android.event.hardware_key"
        "AdvancedKeyEvent" -> "android.event.hardware_key_gesture"
        "CombineKeyEvent" -> "android.event.hardware_key_combo"
        "UsbDeviceAttached", "UsbDeviceDetached" -> "android.event.usb_device_changed"
        "ShakeDevice" -> "android.event.shake"
        "LightSensor", "ProximitySensor", "AccelerometerSensor" -> "android.event.sensor_value"
        else -> null
    }

    fun suggestedActionFeature(typeUrl: String): String? = when (ShortXMappings.shortName(typeUrl)) {
        "ShowToast" -> "android.toast.show"
        "NoAction" -> "core.noop"
        "Delay" -> "core.delay"
        "LaunchApp", "LaunchAppByPkg" -> "android.app.launch"
        "WriteClipboard" -> "android.clipboard.set"
        "ReadClipboard" -> "android.clipboard.get"
        "ShellCommand" -> "android.shell.execute"
        "StopApp", "StopAppByPkg", "StopCurrentApp" -> "android.app.force_stop"
        "InputText" -> "accessibility.input_text"
        "InputTap" -> "accessibility.gesture.tap"
        "InputSwipe" -> "accessibility.gesture.swipe"
        "FindAndClickViewById" -> "accessibility.click_view_id"
        "FindAndClickViewByText", "FindAndClickMatchedView" -> "accessibility.click_text"
        "SetWifiEnabled" -> "android.wifi.set"
        "SetBTEnabled" -> "android.bluetooth.set"
        "SetNFCEnabled" -> "android.nfc.set"
        "SetLocationEnabled" -> "android.location.enabled.set"
        "SetAPMModeEnabled" -> "android.airplane_mode.set"
        "SetDataEnabled" -> "android.mobile_data.set"
        "SetDarkModeEnabled" -> "android.display.dark_mode.set"
        "SetMasterSync" -> "android.sync.master.set"
        "SetRingerMode" -> "android.audio.ringer_mode.set"
        "SetScreenRotate" -> "android.display.rotation.set"
        "SetScreenTimeout" -> "android.display.screen_timeout.set"
        "SetAutoBrightness", "SetBrightness", "ScreenBrightness" -> "android.display.brightness.set"
        "SetFlashLightEnabled" -> "android.torch.set"
        "WakeupScreen" -> "android.screen.wake"
        "SleepScreen" -> "system.screen.sleep"
        "TTS" -> "android.tts.speak"
        "OpenUrl" -> "android.uri.open"
        "InjectKeyCode", "InjectCombineKeyCode" -> "android.input.keyevent"
        "MediaPlayback", "MediaPlaybackAction" -> "android.media.transport"
        "SetDNDEnabled", "ToggleDND" -> "android.dnd.set"
        "Vibrate" -> "android.vibrate"
        "HttpRequest" -> "android.http.request"
        "SetWallpaper" -> "android.wallpaper.set"
        "PostNotification" -> "android.notification.show"
        "RemoveNotification", "RemoveNotificationForPackage", "RemoveNotificationForPackageByPkg" -> "android.notification.dismiss"
        "ClickNotification" -> "android.notification.open"
        "ClickNotificationActionButton" -> "android.notification.action"
        "SetAppEnabled", "SetAppEnabledByPkg", "DisableApp", "DisableAppByPkg" -> "android.app.enabled.set"
        "SetAppInactive", "SetAppInactiveByPkg" -> "android.app.inactive.set"
        "SetAppSuspend", "SetAppSuspendByPkg" -> "android.app.suspended.set"
        "GetAppInfo" -> "android.app.package_info"
        "SetVolume" -> "android.audio.volume.set"
        "AdjustVolume" -> "android.audio.volume.adjust"
        "ShareContent" -> "android.file.share"
        "SendSMS" -> "android.sms.send"
        "StartService", "StopService" -> "android.service.control"
        "LockDeviceNow" -> "system.screen.sleep"
        "ExpandNotification" -> "android.status_bar.control"
        "PlayRingtone" -> "android.audio.play"
        "RequestAudioFocus" -> "android.audio.focus.request"
        "GetScreenOnTime" -> "android.screen_on_time.get"
        "MatchRegex" -> "data.regex.matches"
        "ReplaceRegex" -> "data.regex.replace"
        else -> null
    }

}
