package com.yagay.yauto.ui.editor

import androidx.annotation.StringRes
import com.yagay.yauto.ui.design.R as TextR

/**
 * User-facing names aligned with terminology verified in MacroDroid 5.67.8, ShortX 1.11 and
 * Tasker 6.6.20. Only canonical YAuto features with matching semantics are overridden here.
 * Feature IDs and runtime behavior stay unchanged.
 */
@StringRes
internal fun sourceAlignedFeatureTitle(id: String): Int? = when (id) {
    "core.delay" -> TextR.string.source_feature_name_wait
    "android.app.launch" -> TextR.string.source_feature_name_launch_app
    "android.home.launch" -> TextR.string.source_feature_name_go_home
    "android.vibrate" -> TextR.string.source_feature_name_vibrate
    "android.file.open" -> TextR.string.source_feature_name_open_file
    "android.uri.open" -> TextR.string.source_feature_name_open_url
    "android.clipboard.set" -> TextR.string.source_feature_name_set_clipboard
    "android.clipboard.get" -> TextR.string.source_feature_name_read_clipboard
    "android.http.request" -> TextR.string.source_feature_name_http_request
    "android.shell.execute" -> TextR.string.source_feature_name_run_shell
    "android.email.compose" -> TextR.string.source_feature_name_compose_email
    "android.screen.screenshot" -> TextR.string.source_feature_name_screen_capture
    "android.screenshot.capture" -> TextR.string.source_feature_name_screen_capture
    "accessibility.screenshot.capture" -> TextR.string.source_feature_name_screen_capture
    "android.audio.play" -> TextR.string.source_feature_name_play_audio
    "android.input.keyevent" -> TextR.string.source_feature_name_press_key
    "system.screen.sleep" -> TextR.string.source_feature_name_turn_screen_off
    "android.screen.wake" -> TextR.string.source_feature_name_turn_screen_on
    "android.sms.compose" -> TextR.string.source_feature_name_compose_sms
    "android.audio.speakerphone.set" -> TextR.string.source_feature_name_speakerphone
    "android.bluetooth.set" -> TextR.string.source_feature_name_toggle_bluetooth
    "android.audio.microphone_mute.set" -> TextR.string.source_feature_name_mic_mute
    "android.audio.volume.set" -> TextR.string.source_feature_name_set_volume
    "android.audio.volume.adjust" -> TextR.string.source_feature_name_adjust_volume
    "android.dnd.set" -> TextR.string.source_feature_name_toggle_dnd
    "android.display.rotation.set" -> TextR.string.source_feature_name_screen_rotation
    "android.nfc.set" -> TextR.string.source_feature_name_toggle_nfc
    "android.sync.master.set" -> TextR.string.source_feature_name_auto_sync
    "android.location.enabled.set" -> TextR.string.source_feature_name_toggle_location
    "android.airplane_mode.set" -> TextR.string.source_feature_name_airplane_mode
    "android.app.notification_settings.open" -> TextR.string.source_feature_name_notification_settings
    "android.display.dark_mode.set" -> TextR.string.source_feature_name_toggle_dark_mode
    "android.mobile_data.set" -> TextR.string.source_feature_name_toggle_mobile_data
    "android.wifi.set" -> TextR.string.source_feature_name_toggle_wifi
    "android.torch.set" -> TextR.string.source_feature_name_toggle_flashlight
    "android.network.tether.set" -> TextR.string.source_feature_name_network_tethering
    "android.notification.show" -> TextR.string.source_feature_name_show_notification
    "android.toast.show" -> TextR.string.source_feature_name_show_toast
    "android.tts.speak" -> TextR.string.source_feature_name_say
    "android.alarm.set" -> TextR.string.source_feature_name_set_alarm
    "android.calendar.event.insert" -> TextR.string.source_feature_name_calendar_insert
    "android.notification.cancel" -> TextR.string.source_feature_name_cancel_notification
    "android.display.brightness.set" -> TextR.string.source_feature_name_set_brightness
    "android.display.screen_timeout.set" -> TextR.string.source_feature_name_set_screen_timeout
    "android.power.stay_awake.set" -> TextR.string.source_feature_name_stay_on
    "android.display.auto_rotate.set" -> TextR.string.source_feature_name_auto_rotate
    "android.intent.send" -> TextR.string.source_feature_name_send_intent
    "android.call_log.open" -> TextR.string.source_feature_name_call_log
    "android.car_mode.set" -> TextR.string.source_feature_name_car_mode
    "file.move" -> TextR.string.source_feature_name_move
    "file.copy" -> TextR.string.source_feature_name_copy_file
    "file.delete" -> TextR.string.source_feature_name_delete_file
    "file.mkdir" -> TextR.string.source_feature_name_create_directory
    "file.write_text" -> TextR.string.source_feature_name_write_file
    "file.list" -> TextR.string.source_feature_name_list_files
    "file.read_text" -> TextR.string.source_feature_name_read_file
    "file.archive.zip" -> TextR.string.source_feature_name_zip
    "file.archive.unzip" -> TextR.string.source_feature_name_unzip
    "script.java_function" -> TextR.string.source_feature_name_java_function
    "script.java_object.manage" -> TextR.string.source_feature_name_java_object
    "android.biometric.authenticate" -> TextR.string.source_feature_name_biometric_verify
    "android.audio.record.start" -> TextR.string.source_feature_name_audio_recording
    "android.audio.record.stop" -> TextR.string.source_feature_name_stop_audio_recording
    "android.qs_tile.click" -> TextR.string.source_feature_name_click_qs_tile
    "accessibility.universal_copy.show" -> TextR.string.source_feature_name_universal_copy
    "accessibility.view_id_viewer.show" -> TextR.string.source_feature_name_view_id_lookup
    "android.file.share" -> TextR.string.source_feature_name_share_file
    "android.maps.open" -> TextR.string.source_feature_name_open_map
    "android.adb_wifi.command" -> TextR.string.source_feature_name_adb_wifi
    "android.media.transport" -> TextR.string.source_feature_name_media_control
    "android.wallpaper.set" -> TextR.string.source_feature_name_set_wallpaper
    "android.app.last_used.launch" -> TextR.string.source_feature_name_launch_last_app
    "android.location.current.query" -> TextR.string.source_feature_name_get_current_location
    "android.location.reverse_geocode" -> TextR.string.source_feature_name_get_location_address
    "android.event.screen_on" -> TextR.string.source_feature_name_event_screen_on
    "android.event.screen_off" -> TextR.string.source_feature_name_event_screen_off
    "android.event.user_present" -> TextR.string.source_feature_name_event_screen_unlock
    "android.event.boot" -> TextR.string.source_feature_name_event_device_boot
    "android.event.battery_changed" -> TextR.string.source_feature_name_event_battery_changed
    "android.event.phone_state_changed" -> TextR.string.source_feature_name_event_call_state_changed
    "android.event.sms_received" -> TextR.string.source_feature_name_event_received_text
    "android.event.date_changed" -> TextR.string.source_feature_name_event_date_changed
    "android.event.time_changed" -> TextR.string.source_feature_name_event_time_changed
    "android.event.timezone_changed" -> TextR.string.source_feature_name_event_timezone_changed
    "android.event.storage_low" -> TextR.string.source_feature_name_event_storage_low
    "android.event.locale_changed" -> TextR.string.source_feature_name_event_locale_changed
    "android.event.package_added" -> TextR.string.source_feature_name_event_app_installed
    "android.event.package_removed" -> TextR.string.source_feature_name_event_app_uninstalled
    "android.event.package_replaced" -> TextR.string.source_feature_name_event_app_updated
    "android.event.notification_posted" -> TextR.string.source_feature_name_event_notification_posted
    "android.event.notification_removed" -> TextR.string.source_feature_name_event_notification_removed
    "android.event.notification_updated" -> TextR.string.source_feature_name_event_notification_updated
    "android.event.broadcast" -> TextR.string.source_feature_name_event_intent_received
    "android.event.nfc_tag" -> TextR.string.source_feature_name_event_nfc_tag
    "android.event.clipboard_changed" -> TextR.string.source_feature_name_event_clipboard_change
    "android.event.airplane_mode_changed" -> TextR.string.source_feature_name_event_airplane_mode_changed
    "android.event.bluetooth_state" -> TextR.string.source_feature_name_event_bluetooth_setting
    "android.event.wifi_changed" -> TextR.string.source_feature_name_event_wifi_setting
    "android.event.dark_mode_changed" -> TextR.string.source_feature_name_event_dark_mode_setting
    "android.event.headset_changed" -> TextR.string.source_feature_name_event_headset
    "android.event.location_mode_changed" -> TextR.string.source_feature_name_event_location_setting
    "android.event.power_connected" -> TextR.string.source_feature_name_event_charger_plug
    "android.event.power_disconnected" -> TextR.string.source_feature_name_event_charger_unplug
    "android.event.app_foreground" -> TextR.string.source_feature_name_event_app_foreground
    "android.event.app_background" -> TextR.string.source_feature_name_event_app_background
    "android.event.task_removed" -> TextR.string.source_feature_name_event_task_removed
    "android.event.app_process_started" -> TextR.string.source_feature_name_event_app_started
    "android.event.app_process_stopped" -> TextR.string.source_feature_name_event_app_stopped
    "android.event.system_setting_changed" -> TextR.string.source_feature_name_event_settings_change
    "android.event.system_setting_changed_filtered" -> TextR.string.source_feature_name_event_settings_change
    "android.event.torch_state_changed" -> TextR.string.source_feature_name_event_flashlight_setting
    "android.event.torch_state_changed_filtered" -> TextR.string.source_feature_name_event_flashlight_setting
    "android.event.tethering_changed" -> TextR.string.source_feature_name_event_hotspot_setting
    "android.event.usb_device_changed" -> TextR.string.source_feature_name_event_usb_device_changed
    "android.event.shake" -> TextR.string.source_feature_name_event_shake
    "android.event.mobile_data_changed" -> TextR.string.source_feature_name_event_mobile_data_setting
    "android.event.dnd_filter_changed" -> TextR.string.source_feature_name_event_dnd_changed
    "android.event.orientation_changed" -> TextR.string.source_feature_name_event_orientation_changed
    "android.event.audio_focus_changed" -> TextR.string.source_feature_name_event_audio_focus_changed
    "android.condition.bluetooth_enabled" -> TextR.string.source_feature_name_state_bluetooth
    "android.condition.power_save" -> TextR.string.source_feature_name_state_power_save
    "android.condition.headset_connected" -> TextR.string.source_feature_name_state_headset
    "android.condition.phone_call_state" -> TextR.string.source_feature_name_state_call
    "android.condition.airplane_mode" -> TextR.string.source_feature_name_state_airplane
    "android.condition.screen" -> TextR.string.source_feature_name_state_display
    "android.condition.master_sync" -> TextR.string.source_feature_name_state_auto_sync
    "android.condition.battery_level" -> TextR.string.source_feature_name_state_battery_level
    "android.condition.battery_temperature" -> TextR.string.source_feature_name_state_battery_temperature
    "android.condition.wifi_network" -> TextR.string.source_feature_name_state_wifi_connected
    "android.condition.dark_mode" -> TextR.string.source_feature_name_state_dark_mode
    "android.condition.nfc_enabled" -> TextR.string.source_feature_name_state_nfc
    "android.condition.app_foreground" -> TextR.string.source_feature_name_state_app_foreground
    "android.condition.app_process_running" -> TextR.string.source_feature_name_state_app_running
    "android.condition.charging" -> TextR.string.source_feature_name_state_charge
    "android.condition.charging_source" -> TextR.string.source_feature_name_state_power_source
    "android.condition.memory_available" -> TextR.string.source_feature_name_state_memory_available
    "android.condition.notification_active" -> TextR.string.source_feature_name_state_app_notification
    "android.condition.orientation" -> TextR.string.source_feature_name_state_orientation
    "android.condition.reference.orientation" -> TextR.string.source_feature_name_state_orientation
    "android.condition.ringer_mode" -> TextR.string.source_feature_name_state_ringer_mode
    "android.condition.audio.ringer_mode" -> TextR.string.source_feature_name_state_ringer_mode
    "android.condition.keyguard_locked" -> TextR.string.source_feature_name_state_screen_locked
    "android.condition.device_locked" -> TextR.string.source_feature_name_state_screen_locked
    "android.condition.screen_on_time" -> TextR.string.source_feature_name_state_screen_on_time
    "android.condition.service_running" -> TextR.string.source_feature_name_state_service_running
    "android.condition.torch_on" -> TextR.string.source_feature_name_state_flashlight_on
    "android.condition.keyboard_visible" -> TextR.string.source_feature_name_state_ime_visibility
    "android.condition.notification_panel_expanded" -> TextR.string.source_feature_name_state_notification_panel
    "android.condition.qs_tile_state" -> TextR.string.source_feature_name_state_qs_tile
    "android.condition.mobile_data_enabled" -> TextR.string.source_feature_name_state_mobile_data
    "android.condition.bluetooth_device_connected" -> TextR.string.source_feature_name_state_bt_connected
    "android.condition.calendar_day_type" -> TextR.string.source_feature_name_state_calendar_day
    "android.condition.stay_awake_while_charging" -> TextR.string.source_feature_name_state_stay_awake
    else -> null
}
