package com.yagay.yauto.core.model

import java.util.Locale

/**
 * Stable user-facing message catalog for non-Android core/platform code.
 *
 * Core, importers and diagnostic collectors must not depend on Android R.string.  They emit
 * stable message codes and resolve only the small wrapper sentence here.  Raw shell/logcat/
 * exception details remain untouched so diagnostics stay useful to developers and AI tools.
 */
object UserTextCatalog {
    private val english = mapOf(
        "engine.runtime_limit_positive" to "Runtime limit must be positive",
        "engine.loop_limit_positive" to "Loop limit must be positive",
        "engine.execution_timeout" to "Execution timed out after %s ms",
        "engine.execution_completed" to "Execution completed",
        "engine.execution_failed" to "Execution failed: %s",
        "engine.execution_cancelled" to "Execution cancelled",
        "engine.unknown_action" to "Unknown action: %s",
        "engine.action_failed" to "Action failed: %s",
        "engine.repeat_limit" to "Repeat count exceeds the loop limit or is negative",
        "engine.while_limit" to "While-loop limit exceeded",
        "engine.foreach_limit" to "For-each count exceeds the loop limit",
        "engine.flow_depth" to "Flow call depth exceeds 64",
        "engine.unknown_flow" to "Unknown flow: %s",
        "engine.missing_flow_input" to "Missing required flow input: %s",
        "engine.unknown_condition" to "Unknown condition: %s",
        "runtime.event" to "Runtime event: %s",
        "runtime.no_state_evaluator" to "No state evaluator: %s",
        "runtime.dispatch_failed" to "Automation dispatch failed: %s",
        "runtime.no_condition_evaluator" to "No condition evaluator: %s",
        "runtime.event_source_failed" to "Event source failed to start: %s: %s",
        "diagnostics.collector_failed" to "Collector failed: %s",
        "diagnostics.accessibility.connected" to "YAuto Accessibility Service connected",
        "diagnostics.accessibility.disconnected" to "Accessibility Service not connected",
        "diagnostics.accessibility.title" to "Accessibility backend",
        "diagnostics.accessibility.ready" to "YAuto Accessibility Service is connected and ready",
        "diagnostics.accessibility.not_connected" to "YAuto Accessibility Service is not connected",
        "diagnostics.root.available" to "Root shell available",
        "diagnostics.root.unavailable" to "Root shell unavailable",
        "diagnostics.root.environment" to "Root environment",
        "diagnostics.root.logcat" to "Relevant root logcat",
        "diagnostics.root.kernel" to "Root/kernel messages",
        "diagnostics.lsposed.readable" to "LSPosed data directory readable",
        "diagnostics.lsposed.unreadable" to "LSPosed log directory is not readable through the current backend",
        "diagnostics.lsposed.logs" to "LSPosed logs",
        "diagnostics.execution.available" to "Persistent execution logs available",
        "diagnostics.execution.empty" to "No persistent execution logs yet",
        "diagnostics.execution.log" to "Execution log: %s",
        "diagnostics.import.available" to "Import compatibility reports available",
        "diagnostics.import.empty" to "No import reports yet",
        "diagnostics.import.report" to "Import report: %s",
        "diagnostics.notification.granted" to "Notification listener access granted",
        "diagnostics.notification.denied" to "Notification listener access is not granted",
        "diagnostics.notification.title" to "Notification listener access",
        "diagnostics.enabled" to "Enabled",
        "diagnostics.disabled" to "Disabled",
        "diagnostics.shizuku.connected" to "Shizuku connected and authorized",
        "diagnostics.shizuku.unavailable" to "Shizuku unavailable or permission denied",
        "diagnostics.shizuku.title" to "Shizuku backend",
        "diagnostics.xposed.connected" to "LSPosed system bridge connected",
        "diagnostics.xposed.scope_required" to "Enable YAuto for Android/system_server and restart",
        "diagnostics.xposed.title" to "LSPosed system bridge",
        "capability.shizuku.disconnected" to "Shizuku service disconnected",
        "capability.shizuku.not_running" to "Shizuku is not running",
        "capability.shizuku.permission_denied" to "Shizuku permission is not granted",
        "capability.shell_empty" to "Shell command is empty",
        "capability.timed_out" to "Timed out",
        "capability.lsposed_no_response" to "LSPosed bridge did not respond",
        "import.no_compatible_importer" to "No compatible importer found",
        "import.not_utf8_json" to "The file is not UTF-8 JSON",
        "import.macrodroid.none" to "No MacroDroid macro found in the export",
        "import.macrodroid.block_name" to "Imported Action Block %s",
        "import.macrodroid.macro_name" to "Imported Macro %s",
        "import.macrodroid.block_unresolved" to "Action Block target could not be resolved; the source payload was preserved",
        "import.macrodroid.no_mapping" to "No native YAuto mapping is available yet; the source payload was preserved",
        "import.macrodroid.partial_mapping" to "The native feature type is known, but required source fields or semantics could not be translated; the source payload was preserved",
        "import.macrodroid.failed" to "MacroDroid import failed",
        "import.tasker.task_name" to "Imported Task %s",
        "import.tasker.profile_name" to "Imported Profile %s",
        "import.tasker.context_preserved" to "Tasker context was preserved; a native mapping can be added independently",
        "import.tasker.target_unresolved" to "Perform Task target could not be resolved; the source action was preserved",
        "import.tasker.action_preserved" to "Tasker action was preserved; a native mapping can be added independently",
        "import.tasker.failed" to "Tasker import failed",
        "import.shortx.rule_name" to "Imported ShortX Rule %s",
        "import.shortx.structure_unrecognized" to "No ShortX Rule/RuleList/RuleSetList structure was recognized",
        "import.shortx.payload_preserved" to "ShortX payload was preserved; a native execution mapping is not available yet",
        "import.shortx.failed" to "ShortX import failed",
        "compat.imported_item" to "Imported source item",
        "compat.imported_item_description" to "Preserved source item waiting for a native mapping",
        "compat.imported_action" to "Imported source action",
        "compat.imported_action_description" to "Preserved source action waiting for a native mapping",
        "compat.action_not_mapped" to "Imported action is not mapped yet: %s",
    )

    private val simplifiedChinese = mapOf(
        "engine.runtime_limit_positive" to "运行时间限制必须大于 0",
        "engine.loop_limit_positive" to "循环次数限制必须大于 0",
        "engine.execution_timeout" to "执行超时：已超过 %s 毫秒",
        "engine.execution_completed" to "执行完成",
        "engine.execution_failed" to "执行失败：%s",
        "engine.execution_cancelled" to "执行已取消",
        "engine.unknown_action" to "未知动作：%s",
        "engine.action_failed" to "动作执行失败：%s",
        "engine.repeat_limit" to "重复次数超过循环限制或为负数",
        "engine.while_limit" to "While 循环次数超过限制",
        "engine.foreach_limit" to "逐项循环次数超过限制",
        "engine.flow_depth" to "流程调用深度超过 64 层",
        "engine.unknown_flow" to "未知流程：%s",
        "engine.missing_flow_input" to "缺少必填流程输入：%s",
        "engine.unknown_condition" to "未知条件：%s",
        "runtime.event" to "运行事件：%s",
        "runtime.no_state_evaluator" to "缺少状态求值器：%s",
        "runtime.dispatch_failed" to "自动化分发失败：%s",
        "runtime.no_condition_evaluator" to "缺少条件求值器：%s",
        "runtime.event_source_failed" to "事件源启动失败：%s：%s",
        "diagnostics.collector_failed" to "诊断采集器失败：%s",
        "diagnostics.accessibility.connected" to "YAuto 无障碍服务已连接",
        "diagnostics.accessibility.disconnected" to "无障碍服务未连接",
        "diagnostics.accessibility.title" to "无障碍后端",
        "diagnostics.accessibility.ready" to "YAuto 无障碍服务已连接并可用",
        "diagnostics.accessibility.not_connected" to "YAuto 无障碍服务未连接",
        "diagnostics.root.available" to "Root Shell 可用",
        "diagnostics.root.unavailable" to "Root Shell 不可用",
        "diagnostics.root.environment" to "Root 环境",
        "diagnostics.root.logcat" to "相关 Root Logcat",
        "diagnostics.root.kernel" to "Root / 内核消息",
        "diagnostics.lsposed.readable" to "LSPosed 数据目录可读取",
        "diagnostics.lsposed.unreadable" to "当前后端无法读取 LSPosed 日志目录",
        "diagnostics.lsposed.logs" to "LSPosed 日志",
        "diagnostics.execution.available" to "已有持久化执行日志",
        "diagnostics.execution.empty" to "暂无持久化执行日志",
        "diagnostics.execution.log" to "执行日志：%s",
        "diagnostics.import.available" to "已有导入兼容性报告",
        "diagnostics.import.empty" to "暂无导入报告",
        "diagnostics.import.report" to "导入报告：%s",
        "diagnostics.notification.granted" to "已授予通知监听权限",
        "diagnostics.notification.denied" to "未授予通知监听权限",
        "diagnostics.notification.title" to "通知监听权限",
        "diagnostics.enabled" to "已启用",
        "diagnostics.disabled" to "已禁用",
        "diagnostics.shizuku.connected" to "Shizuku 已连接并授权",
        "diagnostics.shizuku.unavailable" to "Shizuku 不可用或未授权",
        "diagnostics.shizuku.title" to "Shizuku 后端",
        "diagnostics.xposed.connected" to "LSPosed 系统桥接已连接",
        "diagnostics.xposed.scope_required" to "请为 YAuto 勾选 Android/system_server 作用域并重启对应进程",
        "diagnostics.xposed.title" to "LSPosed 系统桥接",
        "capability.shizuku.disconnected" to "Shizuku 服务已断开",
        "capability.shizuku.not_running" to "Shizuku 未运行",
        "capability.shizuku.permission_denied" to "尚未授予 Shizuku 权限",
        "capability.shell_empty" to "Shell 命令为空",
        "capability.timed_out" to "执行超时",
        "capability.lsposed_no_response" to "LSPosed 桥接没有响应",
        "import.no_compatible_importer" to "没有找到兼容的导入器",
        "import.not_utf8_json" to "文件不是 UTF-8 JSON",
        "import.macrodroid.none" to "导出文件中没有找到 MacroDroid 宏",
        "import.macrodroid.block_name" to "导入的动作块 %s",
        "import.macrodroid.macro_name" to "导入的宏 %s",
        "import.macrodroid.block_unresolved" to "无法解析动作块目标；已保留原始数据",
        "import.macrodroid.no_mapping" to "暂时没有对应的 YAuto 原生映射；已保留原始数据",
        "import.macrodroid.partial_mapping" to "已识别原生功能类型，但必要字段或语义暂时无法转换；已保留原始数据",
        "import.macrodroid.failed" to "MacroDroid 导入失败",
        "import.tasker.task_name" to "导入的 Task %s",
        "import.tasker.profile_name" to "导入的配置 %s",
        "import.tasker.context_preserved" to "已保留 Tasker 上下文；以后可以独立增加原生映射",
        "import.tasker.target_unresolved" to "无法解析 Perform Task 目标；已保留原始动作",
        "import.tasker.action_preserved" to "已保留 Tasker 动作；以后可以独立增加原生映射",
        "import.tasker.failed" to "Tasker 导入失败",
        "import.shortx.rule_name" to "导入的 ShortX 规则 %s",
        "import.shortx.structure_unrecognized" to "无法识别 ShortX Rule / RuleList / RuleSetList 结构",
        "import.shortx.payload_preserved" to "已保留 ShortX 数据；暂时没有对应的原生执行映射",
        "import.shortx.failed" to "ShortX 导入失败",
        "compat.imported_item" to "导入的源项目",
        "compat.imported_item_description" to "已保留源项目，等待原生映射",
        "compat.imported_action" to "导入的源动作",
        "compat.imported_action_description" to "已保留源动作，等待原生映射",
        "compat.action_not_mapped" to "导入的动作尚未映射：%s",
    )

    fun text(code: String, fallback: String? = null, vararg args: Any?): String {
        val language = Locale.getDefault().language.lowercase(Locale.ROOT)
        val pattern = if (language == "zh") {
            simplifiedChinese[code] ?: english[code] ?: fallback ?: code
        } else {
            english[code] ?: fallback ?: code
        }
        if (args.isEmpty()) return pattern
        return runCatching { String.format(Locale.getDefault(), pattern, *args) }.getOrElse { pattern }
    }
}

fun userText(code: String, fallback: String? = null, vararg args: Any?): String =
    UserTextCatalog.text(code, fallback, *args)
