package com.yagay.yauto.platform.xposed

/**
 * Clean-room compatibility catalog derived from observed ShortX hook responsibilities.
 * It intentionally contains only class/method identities and YAuto event mappings; hook behavior
 * stays in YAutoXposedModule so every interception remains reviewable and capability-gated.
 */
internal enum class ShortXHookPayloadKind {
    NONE,
    PROCESS,
    ACTIVITY,
    NOTIFICATION,
    VPN,
    IME,
    WINDOW,
    ROTATION,
    WIDGET,
    SHORTCUT,
    STATUS_BAR_ICON,
    INTENT_START,
    SCREEN_STATE,
    BACK_PRESS,
}

internal data class ShortXObserverHookSpec(
    val id: String,
    val classNames: List<String>,
    val methodNames: Set<String>,
    val eventType: String,
    val payloadKind: ShortXHookPayloadKind = ShortXHookPayloadKind.NONE,
    val after: Boolean = false,
)

internal object ShortXCompatHookCatalog {
    val systemServerObservers: List<ShortXObserverHookSpec> = listOf(
        ShortXObserverHookSpec(
            id = "ams-start",
            classNames = listOf(
                "com.android.server.am.ActivityManagerService",
                "com.android.server.am.ActivityManagerService\$Lifecycle",
            ),
            methodNames = setOf("start", "onStart"),
            eventType = "android.event.activity_manager_started",
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "ams-system-ready",
            classNames = listOf("com.android.server.am.ActivityManagerService"),
            methodNames = setOf("systemReady"),
            eventType = "android.event.activity_manager_ready",
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "ams-shell-command",
            classNames = listOf("com.android.server.am.ActivityManagerShellCommand"),
            methodNames = setOf("onCommand"),
            eventType = "android.event.activity_manager_shell_command",
        ),
        ShortXObserverHookSpec(
            id = "input-manager-start",
            classNames = listOf("com.android.server.input.InputManagerService"),
            methodNames = setOf("start"),
            eventType = "android.event.input_manager_started",
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "window-manager-ready",
            classNames = listOf("com.android.server.wm.WindowManagerService"),
            methodNames = setOf("systemReady"),
            eventType = "android.event.window_manager_ready",
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "process-list-start",
            classNames = listOf("com.android.server.am.ProcessList"),
            methodNames = setOf("handleProcessStartedLocked"),
            eventType = "android.event.app_process_started",
            payloadKind = ShortXHookPayloadKind.PROCESS,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "process-list-stop",
            classNames = listOf(
                "com.android.server.am.ProcessList",
                "com.android.server.am.ActivityManagerService",
            ),
            methodNames = setOf("removeLruProcessLocked"),
            eventType = "android.event.app_process_stopped",
            payloadKind = ShortXHookPayloadKind.PROCESS,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "activity-real-start",
            classNames = listOf("com.android.server.wm.ActivityTaskSupervisor"),
            methodNames = setOf("realStartActivityLocked"),
            eventType = "android.event.activity_started",
            payloadKind = ShortXHookPayloadKind.ACTIVITY,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "activity-resumed",
            classNames = listOf(
                "com.android.server.wm.ActivityRecord",
                "com.android.server.wm.ActivityTaskManagerService",
                "com.android.server.am.ActivityRecord",
                "com.android.server.am.ActivityManagerService",
            ),
            methodNames = setOf("activityResumedLocked", "activityResumed"),
            eventType = "android.event.activity_resumed",
            payloadKind = ShortXHookPayloadKind.ACTIVITY,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "activity-state",
            classNames = listOf(
                "com.android.server.wm.ActivityRecord",
                "com.android.server.am.ActivityRecord",
            ),
            methodNames = setOf("setState"),
            eventType = "android.event.activity_state_changed",
            payloadKind = ShortXHookPayloadKind.ACTIVITY,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "activity-stopped",
            classNames = listOf(
                "com.android.server.wm.ActivityRecord",
                "com.android.server.am.ActivityRecord",
            ),
            methodNames = setOf("activityStoppedLocked", "activityStopped"),
            eventType = "android.event.activity_stopped",
            payloadKind = ShortXHookPayloadKind.ACTIVITY,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "activity-launch-request",
            classNames = listOf("com.android.server.wm.ActivityStarter"),
            methodNames = setOf("executeRequest"),
            eventType = "android.event.activity_start_requested",
            payloadKind = ShortXHookPayloadKind.INTENT_START,
        ),
        ShortXObserverHookSpec(
            id = "activity-metrics-launched",
            classNames = listOf("com.android.server.wm.ActivityMetricsLogger"),
            methodNames = setOf("notifyActivityLaunched"),
            eventType = "android.event.activity_launched",
            payloadKind = ShortXHookPayloadKind.ACTIVITY,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "notification-posted",
            classNames = listOf("com.android.server.notification.NotificationUsageStats"),
            methodNames = setOf("registerPostedByApp"),
            eventType = "android.event.notification_posted_system",
            payloadKind = ShortXHookPayloadKind.NOTIFICATION,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "notification-updated",
            classNames = listOf("com.android.server.notification.NotificationUsageStats"),
            methodNames = setOf("registerUpdatedByApp"),
            eventType = "android.event.notification_updated_system",
            payloadKind = ShortXHookPayloadKind.NOTIFICATION,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "notification-removed",
            classNames = listOf("com.android.server.notification.NotificationUsageStats"),
            methodNames = setOf("registerRemovedByApp"),
            eventType = "android.event.notification_removed_system",
            payloadKind = ShortXHookPayloadKind.NOTIFICATION,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "notification-dismissed",
            classNames = listOf("com.android.server.notification.NotificationUsageStats"),
            methodNames = setOf("registerDismissedByUser"),
            eventType = "android.event.notification_dismissed_system",
            payloadKind = ShortXHookPayloadKind.NOTIFICATION,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "vpn-state",
            classNames = listOf("com.android.server.connectivity.Vpn"),
            methodNames = setOf("updateState"),
            eventType = "android.event.vpn_state_changed",
            payloadKind = ShortXHookPayloadKind.VPN,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "ime-show",
            classNames = listOf("com.android.server.inputmethod.InputMethodManagerService"),
            methodNames = setOf("showCurrentInputLocked"),
            eventType = "android.event.ime_shown",
            payloadKind = ShortXHookPayloadKind.IME,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "ime-hide",
            classNames = listOf("com.android.server.inputmethod.InputMethodManagerService"),
            methodNames = setOf("hideCurrentInputLocked"),
            eventType = "android.event.ime_hidden",
            payloadKind = ShortXHookPayloadKind.IME,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "ime-input-start",
            classNames = listOf("com.android.server.inputmethod.InputMethodManagerService"),
            methodNames = setOf("startInputOrWindowGainedFocus"),
            eventType = "android.event.ime_input_started",
            payloadKind = ShortXHookPayloadKind.IME,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "window-focus",
            classNames = listOf(
                "com.android.server.wm.WindowManagerService",
                "com.android.server.wm.WindowState",
            ),
            methodNames = setOf("notifyFocusChanged", "reportFocusChangedSerialized"),
            eventType = "android.event.window_focus_changed",
            payloadKind = ShortXHookPayloadKind.WINDOW,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "window-added",
            classNames = listOf("com.android.server.wm.DisplayPolicy"),
            methodNames = setOf("addWindowLw"),
            eventType = "android.event.window_added",
            payloadKind = ShortXHookPayloadKind.WINDOW,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "display-rotation",
            classNames = listOf("com.android.server.wm.DisplayRotation\$OrientationListener"),
            methodNames = setOf("onProposedRotationChanged"),
            eventType = "android.event.rotation_proposed",
            payloadKind = ShortXHookPayloadKind.ROTATION,
        ),
        ShortXObserverHookSpec(
            id = "widget-listening",
            classNames = listOf("com.android.server.appwidget.AppWidgetServiceImpl"),
            methodNames = setOf("startListening"),
            eventType = "android.event.widget_host_listening",
            payloadKind = ShortXHookPayloadKind.WIDGET,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "shortcut-query",
            classNames = listOf(
                "com.android.server.pm.ShortcutService",
                "com.android.server.pm.LauncherAppsService\$LauncherAppsImpl",
            ),
            methodNames = setOf("getShortcuts"),
            eventType = "android.event.shortcut_query",
            payloadKind = ShortXHookPayloadKind.SHORTCUT,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "shortcut-pin",
            classNames = listOf("com.android.server.pm.ShortcutService"),
            methodNames = setOf("requestPinItem"),
            eventType = "android.event.shortcut_pin_requested",
            payloadKind = ShortXHookPayloadKind.SHORTCUT,
        ),
        ShortXObserverHookSpec(
            id = "shortcut-start",
            classNames = listOf(
                "com.android.server.pm.ShortcutService",
                "com.android.server.pm.LauncherAppsService\$LauncherAppsImpl",
            ),
            methodNames = setOf("startShortcut"),
            eventType = "android.event.shortcut_started",
            payloadKind = ShortXHookPayloadKind.SHORTCUT,
        ),
        ShortXObserverHookSpec(
            id = "task-back-pressed",
            classNames = listOf(
                "com.android.server.wm.TaskOrganizerController",
                "com.android.server.wm.ActivityClientController",
            ),
            methodNames = setOf("handleInterceptBackPressedOnTaskRoot", "onBackPressed"),
            eventType = "android.event.back_pressed_system",
            payloadKind = ShortXHookPayloadKind.BACK_PRESS,
        ),
        ShortXObserverHookSpec(
            id = "package-query",
            classNames = listOf("com.android.server.pm.ComputerEngine"),
            methodNames = setOf("getServiceInfo", "queryIntentActivities", "queryIntentActivitiesInternal"),
            eventType = "android.event.package_query_system",
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "statusbar-icon",
            classNames = listOf("com.android.server.statusbar.StatusBarManagerService"),
            methodNames = setOf("setIcon"),
            eventType = "android.event.status_bar_icon_changed",
            payloadKind = ShortXHookPayloadKind.STATUS_BAR_ICON,
            after = true,
        ),
        ShortXObserverHookSpec(
            id = "service-screen-state",
            classNames = listOf("com.android.server.am.ActiveServices"),
            methodNames = setOf("updateScreenStateLocked"),
            eventType = "android.event.service_screen_state_changed",
            payloadKind = ShortXHookPayloadKind.SCREEN_STATE,
            after = true,
        ),
    )

    val behaviorHooks: List<String> = listOf(
        "AccessibilitySecurityPolicy.checkAccessibilityAccess",
        "AccessibilitySecurityPolicy.canRetrieveWindowsLocked",
        "AccessibilityWindowManager.getDisplayListLocked",
        "AbstractAccessibilityServiceConnection.getWindows",
        "UiAutomationManager.canRetrieveInteractiveWindowsLocked",
        "AccessibilityUserState.suppressingAccessibilityServicesLocked",
        "ClipboardService.clipboardAccessAllowed",
        "ClipboardService.ClipboardImpl.getPrimaryClip",
        "ComputerEngine.getServiceInfo",
        "ComputerEngine.queryIntentActivities",
        "ContextImpl.checkCallingPermission",
        "ShortcutService.getShortcuts",
        "ShortcutService.requestPinItem",
        "ShortcutService.startShortcut",
        "AppWidgetServiceImpl.startListening",
        "RenderNode.addAnimator",
    )

    val packageHookFamilies: Map<String, List<String>> = mapOf(
        "com.android.systemui" to listOf(
            "QSTileHost/QSHostAdapter",
            "CustomTile.handleClick",
            "TileQueryHelper.addTile",
            "LightBarTransitionsController.setIconsDark",
            "PhoneStatusBarView.onFinishInflate",
            "CustomTile.getTileLabel",
            "Tile.getIcon/getLabel",
        ),
        "com.android.nfc" to listOf("NfcService.NfcServiceHandler.dispatchTagEndpoint"),
        "media-provider" to listOf(
            "MediaDocumentsProvider insert",
            "MediaProvider.onCreate",
            "DatabaseHelper.OnFilesChangeListener",
        ),
        "com.android.providers.telephony" to listOf("SmsProvider.onCreate"),
        "ime-process" to listOf("RemoteInputConnectionImpl.commitText"),
    )
}
